<a href="https://colab.research.google.com/github/PriankaKibria17/Coursera-test/blob/main/Bakery_NumPY_CORE_Assignment_Prianka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Teens for a tech club asked to help analyze data for their bake sale. They are hoping to raise $200.

In [ ]:
# Selling prices are 2 dollars brownies, 1 for a cookie, 10 for a cake
# Assigning the values to a list named price
price = [2, 1, 10]
type(price)

list

In [ ]:
# The club sells 17 brownies, 40 cookies and 1 cake
# Assigning the values to a list named quantity_sold
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [ ]:
# importing numpy
import numpy as np 

In [ ]:
# converting a list to a numpy array
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [ ]:
# Now we can perform calculations w/arrays
price_array * quantity_sold_array

array([34, 40, 10])

In [ ]:
# numpy array that corresponds to the cost to make ea. of the items sold at a bake sale
# Price to make ea. item a brownie 0.25, cookie 0.50, cake 5 dollars
cost_array = np.array( [0.25, 0.50, 5.00] )

In [ ]:
# Subtracting to find the profit of ea. item 
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [ ]:
# Identifying which items made a profit greater than $2 per item
# By asking a T/F statement for ea. element
profit_array > 2.00

array([False, False,  True])

In [ ]:
# Need to update that we also sell pies for $7 so we need to update our price array
# the below will not give the output we want because it will add 7 to each of our array
price_array = price_array + 7
print(price_array)

[ 9  8 17]


In [ ]:
# To fix the added 7 to each element we will subtract
price_array = price_array - [7]

In [ ]:
# using the np.append functionto include the value as previously desired
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [ ]:
# you can append multiple values at once to the array in one command using brackets
# note the use of np.append
# Note the use of square brackets in the code that appends all of the values
# adding $4.50 for fudge, $3 for cupcake, $4 for loaf of banana and $9 for tarte
price_array = np.append(price_array,[4.50,3,4,9] )
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
# To check data type of elements within the array
print(price_array.dtype)

float64


In [ ]:
# deleting price from the array
# no tortes
# note the use of np.delete command & indication of what exactly is being deleted
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
# we want to replace an element
# price change for cakes from 10 to 12
# note the index - cake is index 2
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [ ]:
# updating quantity sold array to include 2 pies, 3 trays of fudge, 16 cupcakes, and 5 loaves of BBread
quantity_sold_array = np.append(quantity_sold_array,[2,3,16,5] )
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [ ]:
# editing cookies from 40 to 39
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [ ]:
# Money collected from sales of ea. item at the bake sale
money_collected_bakesale = quantity_sold_array * price_array

In [ ]:
money_collected_bakesale

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [ ]:
quantity_left_over = [0,0,2,1,6,0,2]
type(quantity_left_over)

list

In [ ]:
quantity_left_over = np.array(quantity_left_over)
type(price_array)

numpy.ndarray

In [ ]:
price_discounted = np.array([0,0,0.5,0.5,0.5,0,0.5])
discounted_prices = price_array * price_discounted

In [ ]:
discounted_prices

array([0.  , 0.  , 6.  , 3.5 , 2.25, 0.  , 2.  ])

In [ ]:
clearance_sale = discounted_prices * quantity_left_over

In [ ]:
clearance_sale

array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [ ]:
(clearance_sale + money_collected_bakesale).sum()

213.5